### PR TITLE
CLI

### PR DESCRIPTION
**Pull request by eggplants**
There is already a CLI implemented in receiptio, but it requires puppeteer.
I thought it would be simpler to have a CLI that works with receiptline by itself, so I implemented it.

Conversion from svg into image (`heic`,`heif`,`avif`,`jpeg`,`jpg`,`png`,`raw`,`tiff`,`tif`,`webp`,`gif`,`jp2`,`jpx`,`j2k`,`j2c`) in this PR is impremented with [lovell/sharp](https://github.com/lovell/sharp) (image processor without headless browser) instead of puppeteer.

Please feel free to close this PR if you do not need it!

---

```shellsession
$ npm install && sudo npm link
$ receiptline -V
receiptline version 1.8.0
(C) 2019-, Open Foodservice System Consortium
Licensed under the Apache License, Version 2.0
https://github.com/receiptline/receiptline

$ receiptline -h
Usage: receiptline [options] [source]

Receiptline CLI

Arguments:
  source                     source file

Options:
  -V, --version              output the version number
  -c, --cpl <number>         characters per line (24-48) (default: 48)
  -e, --encoding <encoding>  encoding (choices: "multilingual", "cp437", "cp852", "cp858", "cp860",
                             "cp863", "cp865", "cp866", "cp1252", "cp932", "shiftjis", "cp936",
                             "gb18030", "cp949", "ksc5601", "cp950", "big5", "tis620", default:
                             "cp437")
  -u, --upside-down          upside down
  -s, --spacing              line spacing
  -c, --no-cutting           no paper cutting
  -G, --gradient             image processing for photos
  -g, --gamma <number>       image gamma correction (0.1-10.0) (default: 1.8)
  -b, --threshold <number>   image thresholding (0-255) (default: 128)
  -p, --printer <command>    printer control language (choices: "base", "svg", "escpos", "sii",
                             "citizen", "fit", "impact", "impactb", "starsbcs", "starmbcs",
                             "starmbcs2", "starlinesbcs", "starlinembcs", "starlinembcs2",
                             "emustarlinesbcs", "emustarlinembcs", "emustarlinembcs2",
                             "stargraphic", default: "svg")
  -o, --output <path>        output file (read stdin unless this option is not given)
  -h, --help                 display help for command

$ receiptline example/data/en/receipt.txt -o a.svg
$ curl -s 'https://raw.githubusercontent.com/eggplants/receipts/master/qrcode/code.rl' | receiptline > b.svg
$ receiptline -p png example/data/en/column_border1.txt -o c.png
error: option '-p, --printer <command>' argument 'png' is invalid. Allowed choices are base, svg, escpos, sii, citizen, fit, impact, impactb, starsbcs, starmbcs, starmbcs2, starlinesbcs, starlinembcs, starlinembcs2, emustarlinesbcs, emustarlinembcs, emustarlinembcs2, stargraphic.
```

- with sharp (+`heic`, `heif`, `avif`, `jpeg`, `jpg`, `png`, `raw`, `tiff`, `tif`, `webp`, `gif`, `jp2`, `jpx`, `j2k`, `j2c`)

```shellsession
$ npm install sharp
$ receiptline -h
Usage: receiptline [options] [source]

Receiptline CLI

Arguments:
  source                     source file

Options:
  -V, --version              output the version number
  -c, --cpl <number>         characters per line (24-48) (default: 48)
  -e, --encoding <encoding>  encoding (choices: "multilingual", "cp437", "cp852", "cp858", "cp860",
                             "cp863", "cp865", "cp866", "cp1252", "cp932", "shiftjis", "cp936",
                             "gb18030", "cp949", "ksc5601", "cp950", "big5", "tis620", default:
                             "cp437")
  -u, --upside-down          upside down
  -s, --spacing              line spacing
  -c, --no-cutting           no paper cutting
  -G, --gradient             image processing for photos
  -g, --gamma <number>       image gamma correction (0.1-10.0) (default: 1.8)
  -b, --threshold <number>   image thresholding (0-255) (default: 128)
  -p, --printer <command>    printer control language (choices: "base", "svg", "escpos", "sii",
                             "citizen", "fit", "impact", "impactb", "starsbcs", "starmbcs",
                             "starmbcs2", "starlinesbcs", "starlinembcs", "starlinembcs2",
                             "emustarlinesbcs", "emustarlinembcs", "emustarlinembcs2",
                             "stargraphic", "heic", "heif", "avif", "jpeg", "jpg", "png", "raw",
                             "tiff", "tif", "webp", "gif", "jp2", "jpx", "j2k", "j2c", default:
                             "svg")
  -o, --output <path>        output file (read stdin unless this option is not given)
  -h, --help                 display help for command

$ receiptline -p png example/data/en/column_border1.txt -o c.png
```

- with puppeteer (+`png`, `jpeg`)

```shellsession
$ npm uninstall sharp
$ npm install puppeteer
...

$ receiptline -h
Usage: receiptline [options] [source]

Receiptline CLI

Arguments:
  source                     source file

Options:
  -V, --version              output the version number
  -c, --cpl <number>         characters per line (24-48) (default: 48)
  -e, --encoding <encoding>  encoding (choices: "multilingual", "cp437", "cp852", "cp858", "cp860",
                             "cp863", "cp865", "cp866", "cp1252", "cp932", "shiftjis", "cp936",
                             "gb18030", "cp949", "ksc5601", "cp950", "big5", "tis620", default:
                             "cp437")
  -u, --upside-down          upside down
  -s, --spacing              line spacing
  -c, --no-cutting           no paper cutting
  -G, --gradient             image processing for photos
  -g, --gamma <number>       image gamma correction (0.1-10.0) (default: 1.8)
  -b, --threshold <number>   image thresholding (0-255) (default: 128)
  -p, --printer <command>    printer control language (choices: "base", "svg", "escpos", "sii",
                             "citizen", "fit", "impact", "impactb", "starsbcs", "starmbcs",
                             "starmbcs2", "starlinesbcs", "starlinembcs", "starlinembcs2",
                             "emustarlinesbcs", "emustarlinembcs", "emustarlinembcs2",
                             "stargraphic", "png", "jpeg", default: "svg")
  -o, --output <path>        output file (read stdin unless this option is not given)
  -h, --help                 display help for command

$ receiptline -p png example/data/en/column_border2.txt -o d.png
```

Created SVG:

- `a.svg`:

</img>

- `b.svg`:

</img>

- `c.png`

</img>

- `d.png`

</img>

### CODE REVIEW

**Comment by receiptline** [comment]
Hello!

We have studied on your source code.
The issue of converting with sharp will be solved soon.
(The text in c.png is misaligned.)
Your information has been helpful.

We would like to keep minimum dependencies.
So we think puppeteer and sharp as an option with receiptline.

Thank you!

**Comment by eggplants** [comment]
Thank you for your response!

>So we think puppeteer and sharp as an option with receiptline.

`puppeteer` you wrote is a typo for `prettier`, isn't it? My implementation don't use `puppeteer` and `prettier` is one of `devDependencies`.

And, yes, `sharp` should be moved into `optionalDependencies`. Maybe related: https://github.com/vercel/next.js/pull/18068

**Comment by eggplants** [comment]
I think puppeteer is too big and slow to be used only for converting SVG to png, etc. So it would be better to just use sharp. It would be very nice if only the problem of misaligned images could be solved! I didn't come up with this solution at the time I created this PR...

>The issue of converting with sharp will be solved soon.

Are you saying that there was a problem with the SVG generated by receiptline? If so, I can't wait for the solution to be pushed to master!

**Comment by eggplants** [comment]
I have added puppeteer and sharp support and updated above comments.
Please confirm it.

**Pull request closed without merging**
